spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: http://localhost:3000/
          predicates:
            - Path=/customers/**
        - id: r2
          uri: http://localhost:3001/
          predicates:
            - Path=/products/**
      discovery:
        locator:
          enabled: true
  application:
    name: gateway-service
server:
  port: 8888